version: "3.8"
services:
  postgres:
    image: postgres:11
    networks:
      tg2sip:
        ipv4_address: 10.5.0.2
    volumes:
      - postgres_db:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_DB=tg2sipdemo
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres

  tg2sip-demo-console:
    image: hectorvent/tg2sip-demo-backend
    networks:
      tg2sip:
        ipv4_address: 10.5.0.3
    environment:
      - DB_USER=value
      - TG2SIP_IP=10.5.0.5
      - FREESWITCH_IP=10.5.0.4
      - POSTGRES_HOST=postgres
      - TG2SIPDEMO_TELEGRAM_BOT_TOKEN=${TELEGRAM_BOT_TOKEN}

  freeswitch:
    image: hectorvent/tg2sip-freeswitch
    networks:
      tg2sip:
        ipv4_address: 10.5.0.4

  tg2sip:
    image: hectorvent/tg2sip-gateway
    volumes:
      - tg2sip:/etc/tg2sip/
    networks:
      tg2sip:
        ipv4_address: 10.5.0.5

volumes:
  postgres_db:

networks:
  tg2sip:
    driver: bridge
    ipam:
     config:
       - subnet: 10.5.0.0/16
         gateway: 10.5.0.1
