#!/usr/bin/env ansible-playbook
---
- hosts: tg2sip-demo
  tasks:
    - name: install tg2sip dependencies
      apt:
        update_cache: yes
        name:
         - libopus0
         - libssl1.1

    - name: download tg2sip debian 10 (buster) build and extract it
      unarchive:
        src: https://github.com/hectorvent/tg2sip/releases/download/v1.2.0/tg2sip-1.2.0-debian10-buster.tar.xz
        dest: /usr/local/bin/
        remote_src: yes

    - name: set executable permissions to files
      file:
        path: /usr/local/bin/{{ item }}
        mode: '777'
      with_items:
        - gen_db
        - tg2sip

    - name: copy tg2sip systemctl service file
      copy:
        src: tg2sip/tg2sip.service
        dest: /etc/systemd/system/tg2sip.service

    - name: ensure data folder exists
      file:
        path: "{{ item }}"
        state: directory
      with_items:
        - /var/tg2sip
        - /etc/tg2sip

    - name: copy tg2sip setting file
      template:
        src: tg2sip/settings.ini.j2
        dest: /etc/tg2sip/settings.ini

    # TODO: create tg2sip user
    - name: restart tg2sip server
      systemd:
        name: tg2sip
        state: restarted
        daemon_reload: yes
